config/routes.rb
Rails.application.routes.draw do
  resources :images
  get 'categories/index_admin'
  get 'categories/show_admin/:id' => 'categories#show_admin'
  resources :categories
  devise_for :accounts
  as :accounts do
    get 'accounts/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'accounts' => 'devise/registrations#update', :as => 'user_registration'
  end
  root to: 'posts#index'
  get 'admins/top'
  resources :admins
  resources :posts
  get 'posts/post_categories' => 'posts#post_categories'
  resources :portfolios
  resources :contacts
  resources :comments
end

app/views/admins/edit.html.erb
<div class="container">
	<h2>投稿編集画面</h2>
	<%= form_with(model:@post, url: admin_path , local: true, multipart: true) do |form| %>
	<% if @post.errors.any? %>
	<div id="error_explanation">
		<h2>
			<%= pluralize(@post.errors.count, "error") %> prohibaited this post from being saved:</h2>
		<ul>
			<% @post.errors.full_messages.each do |message| %>
			<li>
				<%= message %>
			</li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<div class="form-group">
		<div class="field">
			<%= form.label :title %>
			<%= form.text_field :title, id: :post_title, :class=>"form-control" %>
		</div>

		<div class="field mb-2">
			<%= form.label :image %>
			<%= form.file_field :image, id: :image_title, :class=>"form-control-file" %>
		</div>

		<div class="field">
			<%= form.label :content %>
			<%= form.text_area :content, id: :content, :rows=>"3",  :class=>"form-control" %>
		</div>

		<div class="actions mt-2">
			<%= form.submit :class=>"btn btn-primary" %>
		</div>


	</div>
	<% end %>
</div>

app/views/admins/index.html.erb
<div class="container mt-5 mb-5">
<h2>記事一覧</h2>
 <% @posts.each do | post | %>
  <div class="row">
    <div class="col-2 border p-2">
			<% if post.image.attached? %>
				<%= image_tag(post.image, :width => "100%") %>
			<% end %>
    </div>
    <div class="col-8 border">
	  <%= post.title %><br>
	  <%= post.created_at.strftime('%Y年%m月%d日 %H:%M') %>
	</div>
	<div class="col-2  border p-2 border-none ">
		<ul class="list-group">
			<li class="list-group-item border-0">
				<%= link_to 'show', post , class: "btn btn-dark"%>
			</li>
			<li class="list-group-item border-0">
				<%= link_to 'edit', edit_admin_path(post) , class: "btn btn-dark"%>
			</li>
			<li class="list-group-item border-0">
				<%= link_to 'delete', admin_path(post) , method: :delete,  class: "btn btn-dark", data: { confirm: 'are you sure?' }%>
			</li>
		</ul>
    </div>
  </div>
	<% end %>
	<div class="mt-2"><%= paginate @posts%></div>
	<%= link_to 'new', new_admin_path , class: "btn btn-dark mt-2"%>
</div>

app/views/admins/new.html.erb
<div class="container">
	<h2>新規投稿画面</h2>
<%= form_with(model:@post, url: admins_path, local: true, method: :post ,multipart: true) do |form| %>
<% if @post.errors.any? %>
<div id="error_explanation">
	<h2>
		<%= pluralize(@post.errors.count, "error") %> prohibaited this post from being saved:</h2>
	<ul>
		<% @post.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="form-group">
	<%= form.label :タイトル %>
	<%= form.text_field :title, id: :post_title, :class=>"form-control" %>
</div>

<div class="form-group">
	<%= form.label :画像 %>
	<%= form.file_field :image, id: :image_title, :class=>"form-control-file" %>
</div>

<div class="form-group">
	<%= form.label :本文 %>
	<%= form.text_area :content, id: :content, :rows=>"3",:class=>"form-control" %>
</div>

<div class="actions mt-2">
	<%= form.submit "送信" ,:class=>"btn btn-primary" %>
</div>

</div>
<% end %>
</div>

app/views/admins/top.html.erb
<div class="container">
	<h2 class="m-2">管理画面トップ</h2>
	<ul class="list-group mb-2">
		<li class="list-group-item bg-dark text-white">記事</li>
		<li class="list-group-item">
			<%= link_to '記事一覧', admins_path ,class: "text-dark"	%>
		</li>
		<li class="list-group-item">
			<%= link_to '記事追加', new_admin_path ,class: "text-dark"	%>
		</li>
	</ul>
	<ul class="list-group mb-2">
		<li class="list-group-item bg-dark text-white">カテゴリー</li>
		<li class="list-group-item">
			<%= link_to 'カテゴリー一覧', categories_index_admin_path ,class: "text-dark"	%>
		</li>
		<li class="list-group-item">
			<%= link_to 'カテゴリー追加', new_category_path ,class: "text-dark"	%>
		</li>
	</ul>
	<ul class="list-group mb-2">
		<li class="list-group-item bg-dark text-white">画像</li>
		<li class="list-group-item">
			<%= link_to '画像一覧', images_path	,class: "text-dark"	%>
		</li>
		<li class="list-group-item">
			<%= link_to '画像追加', new_image_path ,class: "text-dark" %>
		</li>
	</ul>
	<ul class="list-group mb-2">
		<li class="list-group-item bg-dark text-white">アカウント</li>
		<li class="list-group-item">
			<%= link_to 'アカウント編集', edit_user_registration_path,class: "text-dark" %>
		</li>
	</ul>
</div>