config/routes.rb
Rails.application.routes.draw do
  resources :images
  get 'categories/index_admin'
  get 'categories/show_admin/:id' => 'categories#show_admin'
  resources :categories
  devise_for :accounts
  as :accounts do
    get 'accounts/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'accounts' => 'devise/registrations#update', :as => 'user_registration'
  end
  root to: 'posts#index'
  get 'admins/top'
  resources :admins
  resources :posts
  get 'posts/post_categories' => 'posts#post_categories'
  resources :portfolios
  resources :contacts
  resources :comments
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :title, presence: true
  validates :memo, presence: true
  has_many :post
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :authenticate_account!, except: :index
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  def index_admin
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @posts = @category.post
  end

  def show_a
    @category = Category.find(params[:id])
    @posts = @category.post
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to '/categories/index_admin', notice: 'カテゴリーの作成に成功しました！' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to '/categories/index_admin', notice: '更新に成功しました！' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to '/categories/index_admin', notice: '削除に成功しました。' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:title, :memo)
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title ,required: true, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :memo %>
    <%= form.text_area :memo ,required: true, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "送信" ,class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
<h1>カテゴリー編集</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category ,class: "badge badge-dark" %> |
<%= link_to 'Back', categories_path ,class: "badge badge-dark" %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <h1>カテゴリー一覧</h1>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Title</th>
        <th scope="col">Memo</th>
        <th scope="col">Link</th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
      <tr>
        <th>
          <%= category.id %>
        </th>
        <td>
          <%= category.title %>
        </td>
        <td>
          <%= category.memo %>
        </td>
        <td>
          <%= link_to "関連記事" , category_path(category)%>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/index_admin.html.erb
<div class="container">
<h1>カテゴリー一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Memo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.memo %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<New Category', new_category_path , class: "badge badge-dark"%>

</div>

app/views/categories/new.html.erb
<div class="container">
<h1>カテゴリー登録</h1>
<%= render 'form', category: @category %>
<%= link_to '<Back', categories_path, class: "badge badge-dark" %>
</div>

app/views/categories/show.html.erb
<div class="container">
  <h2><%= @category.title %>の記事一覧</h2>
  <div class="comment  mb-1">
          <table class="table">
              <tr>
                <th scope="col">Title</th>
                <th>content</th>
              </tr>
            <% @posts.each do |post| %>
              <tr>
                <td scope="row">
                  <%= post.title %>
                </td>
                <td>
                  <%= post.content %>
                </td>
              </tr>
            <% end %>

          </table>  
    </div>



</div>

app/views/categories/show_admin.html.erb
<div class="container">
    <p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @category.memo %>
</p>

<%= link_to 'Edit', edit_category_path(@category)  , class: "badge badge-dark"%> |
<%= link_to 'Back', categories_path  , class: "badge badge-dark"%>

</div>