config/routes.rb
Rails.application.routes.draw do
  resources :images
  get 'categories/index_admin'
  get 'categories/show_admin/:id' => 'categories#show_admin'
  resources :categories
  devise_for :accounts
  as :accounts do
    get 'accounts/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'accounts' => 'devise/registrations#update', :as => 'user_registration'
  end
  root to: 'posts#index'
  get 'admins/top'
  resources :admins
  resources :posts
  get 'posts/post_categories' => 'posts#post_categories'
  resources :portfolios
  resources :contacts
  resources :comments
end

app/models/image.rb
class Image < ApplicationRecord
  has_one_attached :image
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_account!
  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.create params.require(:image).permit(:name, :image) # POINT
    redirect_to @image
  end

  def show
    @image = Image.find(params[:id])
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    @image.update params.require(:image).permit(:name, :image) # POINT
    redirect_to @image
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to images_path, notice: 'Post was successfully destroyed.'
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/edit.html.erb
<div class="container p-3">
	<h2>画像の編集</h2>
	<%= form_with model: @image, local: true  do |form| %>
	<div class="form-group">
		<%= form.label :名前 %>
		<%= form.text_field :name ,class: "form-control" %><br>
		<%= form.file_field :image ,class: "form-control-file" %><br>
		<%= form.submit class: "btn btn-primary" %>
	</div>
	<% end %>
</div>

app/views/images/index.html.erb
<div class="container">
<h1>画像</h1>

<table class="table">
  <thead>
    <tr>
      <th>name</th>
      <th>image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
		<td><%= image.name %></td>
		<% if image.image.attached? %>
		<td> <%= image_tag image.image ,width: "100px" %> </td>
		<% end %>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<New Image', new_image_path , class: "badge badge-dark"%>

</div>

app/views/images/new.html.erb
<div class="container mb-1">
<h2>画像新規投稿</h2>
<%= form_with model: @image, local: true  do |form| %>
<div class="form-group"> 
  <%= form.label :名前 %>	
  <%= form.text_field :name ,class: "form-control" %><br>
  <%= form.file_field :image ,class: "form-control-file" %><br>
  <%= form.submit class: "btn btn-primary" %>
 </div>
<% end %>
</div>

app/views/images/show.html.erb
<div class="container">
<h2><%= @image.name %></h2>
<% if @image.image.attached? %>
   <%= image_tag @image.image ,class: "img-fluid p-3" %> 
<% end %>
<p>投稿日：<%= @image.created_at.strftime('%Y年%m月%d日 %H:%M') %></p>
</div>