config/routes.rb
Rails.application.routes.draw do
  resources :images
  get 'categories/index_admin'
  get 'categories/show_admin/:id' => 'categories#show_admin'
  resources :categories
  devise_for :accounts
  as :accounts do
    get 'accounts/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'accounts' => 'devise/registrations#update', :as => 'user_registration'
  end
  root to: 'posts#index'
  get 'admins/top'
  resources :admins
  resources :posts
  get 'posts/post_categories' => 'posts#post_categories'
  resources :portfolios
  resources :contacts
  resources :comments
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="bg-dark">
		<div class="container text-center p-3">
			<%= link_to "https://twitter.com/sumiya113" , target: "brank" do %>
			<%= image_tag "social-twitter", :alt=>"Twitter", :class=>"footer__icon" %>
			<% end %>
			<%= link_to "https://github.com/sumiya19", target: "brank" do %>
			<%= image_tag "social-github", :alt=>"github", :class=>"footer__icon" %>
			<% end %>
			<%= link_to "https://www.instagram.com/sumiya113/", target: "brank" do %>
			<%= image_tag "social-instagram.svg", :alt=>"instagram", :class=>"footer__icon" %>
			<% end %>
			<%= image_tag "social-facebook.svg", :alt=>"facebook", :class=>"footer__icon" %>
			<div class="text-white ">
			</div>
		</div>
	</div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar navbar-expand-lg navbar-light bg-white">
		<div class="container d-flex justify-content-between">
			<%= link_to 'Smalog', posts_path , class: "navbar-brand text-dark" %>
			<button class="navbar-toggler text-dark" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
			 aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav">
					<li class="nav-item">
						<%= link_to 'カテゴリー', categories_path , class: "nav-link text-dark" %>
					</li>
					<li class="nav-item">
					<li class="nav-item">
						<%= link_to 'ポートフォリオ', portfolios_path, class: "nav-link text-dark" %>
					</li>
					<% if current_account %>
					<%= link_to '管理画面', admins_top_path	 , class: "nav-link text-dark" %>
					</li>
					<li class="nav-item">
						<%= link_to 'ログアウト', destroy_account_session_path, method: :delete , class: "nav-link text-dark" %>
					</li>
					<% else %>

					<%end%>

				</ul>
			</div>
	</nav>
	<div class="header-title bg-dark p-5">
		<div class="container text-center text-white">
				<h2><%= yield(:title) || 'SMALOG' %></h2> 
		</div>
	</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>MyBlog</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">

</head>
<body>
  <% if flash[:notice] %>
  <div class="alert alert-primary" role="alert">
      <%= notice %>
  </div>
  <% end %>
  <% if flash[:alert] %>
  <div class="alert alert-success" role="alert">
      <%= alert %>
</div>
  <% end %>
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>

</html>